# Generated by Django 5.0.1 on 2024-01-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='start_course',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
