# Generated by Django 5.0.1 on 2024-01-08 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200, unique=True)),
                ('expiration_time', models.DateField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='lessons.course')),
            ],
        ),
    ]
