# Generated by Django 5.0.1 on 2024-01-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='token',
            field=models.CharField(max_length=200),
        ),
    ]
