# Generated by Django 5.0.1 on 2024-01-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_tokens_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
