# Generated by Django 5.0.1 on 2024-01-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tokens_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
