# Generated by Django 5.0.1 on 2024-01-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.CharField(default='2', max_length=200),
            preserve_default=False,
        ),
    ]
