# Generated by Django 5.0.1 on 2024-01-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_rename_link_course_teacher_course_coupon_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='coupon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
